{
 "title": "Logprep Overview",
 "tags": [ "App" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Behavior Over Selected Timeframe",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Throughput",
   "type": "stat",
   "description": "Throughput of logprep in events per second.",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(logprep_number_of_processed_events_total{component=\"input\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Processing Times",
   "type": "stat",
   "description": "Duration of all connector and pipeline processing times combined.",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg by (component)((increase(logprep_processing_time_per_event_sum{component=~\"input|output|pipeline\"}[$__range])/increase(logprep_processing_time_per_event_count{component=~\"input|output|pipeline\"}[$__range]) > 0)))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Processing Times",
   "type": "stat",
   "description": "Processing times of input connector. When using kafka input connector then 100 ms is equivalent to the timeout of the input connector, meaning no new messages were fetched. ",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"input\"}[$__range])/increase(logprep_processing_time_per_event_count{component=\"input\"}[$__range]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processor Processing Times",
   "type": "stat",
   "description": "Average over all processors when actively working (matched rules).",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"rule\"}[$__range])/increase(logprep_processing_time_per_event_count{component=\"rule\"}[$__range]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Processing Times",
   "type": "stat",
   "description": "Is the sum of the whole pipeline: parsing event, passing it through the pipeline and sending it to the output connector.",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"pipeline\"}[$__range])/increase(logprep_processing_time_per_event_count{component=\"pipeline\"}[$__range]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Processing Times",
   "type": "stat",
   "description": "Average processing times of all output connectors",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{component=\"output\"}[$__range])/increase(logprep_processing_time_per_event_count{component=\"output\"}[$__range])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "The increase of number of errors in the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(logprep_number_of_errors_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logprep Version",
   "type": "stat",
   "description": "Shows the currently active logprep version.",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(logprep_version_info) by (logprep, config)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Config Version",
   "type": "stat",
   "description": "Shows the currently active config version of logprep, if specified.",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(logprep_version_info) by (logprep, config)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pipeline Starts/Stops",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(logprep_number_of_pipeline_starts_total[$__range])))",
     "legendFormat": "Starts"
    },
    {
     "expr": "sum(round(increase(logprep_number_of_pipeline_stops_total[$__range])))",
     "legendFormat": "Stops"
    }
   ]
  },
  {
   "title": "Incoming Events",
   "type": "stat",
   "description": "The increase of incoming events over the selected time frame. ",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"input\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outgoing Events",
   "type": "stat",
   "description": "The increase of outgoing events in the selected time frame. ",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"output\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input/Output Difference",
   "type": "stat",
   "description": "Shows the absolute and relative change between the output and input connector. If using one input and output connector then the relative difference should be close to 1, except for deleted events. When using two outputs and only one input the relative difference should be around 2, because every event will be send to two outputs.",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"input\"}[$__range])) - sum(increase(logprep_number_of_processed_events_total{component=\"output\"}[$__range]))",
     "legendFormat": "Absolut"
    },
    {
     "expr": "sum(increase(logprep_number_of_processed_events_total{component=\"output\"}[$__range])) / sum(increase(logprep_number_of_processed_events_total{component=\"input\"}[$__range])>0)",
     "legendFormat": "Relative"
    }
   ]
  },
  {
   "title": "Number of Rules",
   "type": "stat",
   "description": "The count of the number of rules at the last moment of the selected time frame.",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(count by(pod) (logprep_number_of_processed_events_total{component=\"rule\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of SREs",
   "type": "stat",
   "description": "The increase of number of SREs in the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ceil(sum by(type) (increase(logprep_number_of_processed_events_total{component=\"rule\", type=\"pre_detector\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warnings",
   "type": "stat",
   "description": "The increase of number of warnings in the selected time range",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(logprep_number_of_warnings_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config Refresh Interval",
   "type": "stat",
   "description": "Shows the current config refresh interval.",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(logprep_config_refresh_interval) by (logprep, config)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "description": "Shows the number of config reloads in the selected time frame.",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(logprep_number_of_config_refreshes_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Pipelines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(round(increase(logprep_number_of_failed_pipelines_total[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Active Alarms", "type": "alertlist", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 } },
  {
   "title": "Processing Times for kafka input",
   "type": "stat",
   "description": "Shows the average processing time of the confluent kafka input over the selected time frame.",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{type=\"confluentkafka_input\"}[$__range])/increase(logprep_processing_time_per_event_count{type=\"confluentkafka_input\"}[$__range])>0)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Processing Times for opensearch output",
   "type": "stat",
   "description": "Shows the average processing time of the opensearch output over the selected time frame.",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{type=\"opensearch_output\"}[$__range])/increase(logprep_processing_time_per_event_count{type=\"opensearch_output\"}[$__range])>0)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Processing Times for kafka output",
   "type": "stat",
   "description": "Shows the average processing time of the confluent kafka output over the selected time frame.",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(increase(logprep_processing_time_per_event_sum{type=\"confluentkafka_output\"}[$__range])/increase(logprep_processing_time_per_event_count{type=\"confluentkafka_output\"}[$__range])>0)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Failed Events",
   "type": "stat",
   "description": "Number of events that had an error during processing and which were send to the error output/index.",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_number_of_failed_events_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC/s",
   "type": "stat",
   "description": "Number of garbage collections per second",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(python_gc_collections_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "error queue",
   "type": "stat",
   "description": "Number of events in error queue",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logprep_number_of_events_in_error_queue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "description": "Currently assigned kafka partitions",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (description) (logprep_confluent_kafka_input_committed_offsets))",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Commit failures",
   "type": "stat",
   "description": "Number of unsuccessful Kafka commits",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_confluent_kafka_input_commit_failure_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commit success",
   "type": "stat",
   "description": "Number of successful Kafka commits",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(logprep_confluent_kafka_input_commit_success_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Connectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Processed Event Rate per Connector per Second",
   "type": "timeseries",
   "description": "Shows the per-second average of processed events per connector.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(type)(rate(logprep_number_of_processed_events_total{component=\"input\"}[1m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by(type)(rate(logprep_number_of_processed_events_total{component=\"output\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Success/Failed Event Rate per Output per Second",
   "type": "timeseries",
   "description": "Shows the difference between processed and failed events as a per-second average. Failed events are events that couldn't be parsed or where processors/rules canceled the processing due to an error. ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(logprep_number_of_processed_events_total{component=\"output\"}[1m]))",
     "legendFormat": "Processed Events"
    },
    {
     "expr": "sum(rate(logprep_number_of_failed_events_total{component=\"output\"}[1m]))",
     "legendFormat": "Failed Events"
    }
   ]
  },
  {
   "title": "Processing Time Per Connector",
   "type": "timeseries",
   "description": "Shows the processing time per connector ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (type)(increase(logprep_processing_time_per_event_sum{component=\"input\"}[1m])/increase(logprep_processing_time_per_event_count{component=\"input\"}[1m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by (type)(increase(logprep_processing_time_per_event_sum{component=\"output\"}[1m])/increase(logprep_processing_time_per_event_count{component=\"output\"}[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Offsets",
   "type": "table",
   "description": "Committed and current offsets reported by the librdkafka library",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "logprep_confluent_kafka_input_committed_offsets",
     "legendFormat": "{{description}}"
    },
    {
     "expr": "logprep_confluent_kafka_input_current_offsets",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Recieved Messages in librdkafka",
   "type": "timeseries",
   "description": "Shows how many message the underlying kafka client received as a per-second average.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(logprep_confluent_kafka_input_librdkafka_rxmsgs[1m]))",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Transmitted Messages librdkafka",
   "type": "timeseries",
   "description": "Shows how many message the underlying kafka client transmitted back to kafka as a per-second average.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(logprep_confluent_kafka_output_librdkafka_txmsgs[1m]))",
     "legendFormat": "Messages"
    }
   ]
  },
  {
   "title": "Rate of Input Connector Rebalancing",
   "type": "timeseries",
   "description": "Shows the rate of the kafka consumer group rebalancing of the input connector",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (component) (increase(logprep_confluent_kafka_input_librdkafka_cgrp_rebalance_cnt[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Rate of Applied Rules per Processor per Second",
   "type": "timeseries",
   "description": "Shows a per-second average of the applied rules, aggregated by processor.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by(name) (rate(logprep_number_of_processed_events_total{component=\"rule\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Times per Processor per Second",
   "type": "timeseries",
   "description": "Shows the processing times of matched rules.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (name)(rate(logprep_processing_time_per_event_sum{component=\"rule\"}[1m]))/sum by(name)(rate(logprep_processing_time_per_event_count{component=\"rule\"}[1m]))",
     "legendFormat": "{{description}}"
    }
   ]
  },
  { "title": "Processing Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "Processing Times per Processor per Second",
   "type": "piechart",
   "description": "in relation to each other",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (name)(rate(logprep_processing_time_per_event_sum{component=\"rule\"}[1m]))/sum by(name)(rate(logprep_processing_time_per_event_count{component=\"rule\"}[1m])>0)",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Avg Processing Times per Rule-Type",
   "type": "bargauge",
   "description": "Shows the processing times of matched rules aggregated for each processor. If processor is missing then no data is available in the selected time frame",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum by (name)(rate(logprep_processing_time_per_event_sum{component=\"rule\"}[$__range])))/sum by(name)(rate(logprep_processing_time_per_event_count{component=\"rule\"}[$__range])>0)",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Top 10 Slowest Rules",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (description)(rate(logprep_processing_time_per_event_sum{component=\"rule\"}[$__range]))/sum by(description)(rate(logprep_processing_time_per_event_count{component=\"rule\"}[$__range])>0)",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "Rule Processing Times",
   "type": "heatmap",
   "description": "Shows the processing time of applied rules as a heatmap. The y-axis shows buckets of a histogram and the color intensity shows how many rules where applied per bucket.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "sum(increase(logprep_processing_time_per_event_bucket{component=\"rule\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Errors / Warnings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "Number of Errors",
   "type": "timeseries",
   "description": "in the selected time range",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (component) (increase(logprep_number_of_errors_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Warnings",
   "type": "timeseries",
   "description": "in the selected time range",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (component) (increase(logprep_number_of_warnings_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Warnings per Processor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name) (increase(logprep_number_of_warnings_total{component=\"rule\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}